import { supabase } from '@/integrations/supabase/client';
const SUPABASE_URL=import.meta.env.VITE_SUPABASE_URL as string;
export type HanchiMessage={id:string;role:'user'|'assistant'|'system';content:string;created_at?:string;metadata?:Record<string,unknown>|null};
export type HanchiArtifact={id:string;title:string;file_name:string;mime_type:string;language?:string|null;content:string;version:number;artifact_type:string;preview_mode:string;metadata?:Record<string,unknown>|null;project_id?:string|null;conversation_id?:string|null;updated_at?:string};
export async function getSessionToken(){const {data}=await supabase.auth.getSession();return data.session?.access_token??null;}
export async function edgeRequest<T=unknown>(functionName:string,init:RequestInit={}):Promise<T>{const token=await getSessionToken();if(!token)throw new Error('Your Hanchi session has expired. Please sign in again.');const headers:any={Authorization:`Bearer ${token}`,...(init.body instanceof FormData?{}:{'Content-Type':'application/json'}),...(init.headers||{})};const res=await fetch(`${SUPABASE_URL}/functions/v1/${functionName}`,{...init,headers});const body=await res.text();let payload:any=null;try{payload=body?JSON.parse(body):null}catch{payload=body;}if(!res.ok)throw new Error(payload?.error||payload?.message||(typeof payload==='string'?payload:`Request failed (${res.status})`));return payload;}
export async function streamChat(body:Record<string,unknown>,onDelta:(chunk:string)=>void,onMetadata?:(m:Record<string,unknown>)=>void){const token=await getSessionToken();if(!token)throw new Error('Your Hanchi session has expired. Please sign in again.');const res=await fetch(`${SUPABASE_URL}/functions/v1/chat`,{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify(body)});if(!res.ok||!res.body){const t=await res.text();let p:any=null;try{p=t?JSON.parse(t):null}catch{}throw new Error(p?.error||t||`Chat request failed (${res.status})`);}const reader=res.body.getReader();const dec=new TextDecoder();let buf='';while(true){const {done,value}=await reader.read();if(done)break;buf+=dec.decode(value,{stream:true});const lines=buf.split('\n');buf=lines.pop()||'';for(const line of lines){if(!line.startsWith('data:'))continue;const raw=line.slice(5).trim();if(!raw||raw==='[DONE]')continue;try{const e=JSON.parse(raw);const d=e?.choices?.[0]?.delta?.content;if(typeof d==='string'&&d)onDelta(d);if(e?.metadata&&typeof e.metadata==='object')onMetadata?.(e.metadata);}catch{}}}}
export function downloadTextFile(name:string,content:string,mime='text/plain'){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([content],{type:mime}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500);}
export function extractCodeArtifacts(md:string){const out:Array<{language:string;content:string;fileName:string}>=[];const re=/```([\w+-]*)\n([\s\S]*?)```/g;const ext:any={html:'html',css:'css',js:'js',javascript:'js',ts:'ts',typescript:'ts',tsx:'tsx',jsx:'jsx',json:'json',python:'py',py:'py',sql:'sql',bash:'sh',sh:'sh',markdown:'md',md:'md'};let m:any,i=1;while((m=re.exec(md))){const language=m[1]||'text';out.push({language,content:m[2].replace(/\n$/,''),fileName:`hanchi-artifact-${i}.${ext[language.toLowerCase()]||'txt'}`});i++;}return out;}
export function artifactFromCodeBlock(language:string,content:string,title?:string):HanchiArtifact{const n=language.toLowerCase();const ext:any={html:'html',css:'css',js:'js',javascript:'js',ts:'ts',typescript:'ts',tsx:'tsx',jsx:'jsx',json:'json',py:'py',python:'py',sql:'sql',md:'md',markdown:'md',sh:'sh',bash:'sh'};const e=ext[n]||'txt';const preview=n==='html'?'html':n==='md'||n==='markdown'?'markdown':'code';return{id:`local-${Date.now()}`,title:title||`Hanchi ${n||'text'} artifact`,file_name:`hanchi-${Date.now()}.${e}`,mime_type:preview==='html'?'text/html':preview==='markdown'?'text/markdown':'text/plain',language:language||'text',content,version:1,artifact_type:'generated',preview_mode:preview};}
