// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://udskndcqxhzbutrqkslr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVkc2tuZGNxeGh6YnV0cnFrc2xyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODgwMzcyMTcsImV4cCI6MjEwMzYxMzIxN30.PwMCn4j-Him9eOxdKGwEGVJvk3P4I9NTDKq-deZ-CuA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});